### ISSUE TITLE
[Suggestion] Possibility to escape a point to avoid adding a new JsonObject

### ISSUE THREAD

**Issue by vinc3nz** [CrAfTsArMy/CraftsCore#2]
For example if i have a point in a string, i want to escape it by using a backslash
Example: 
`versions.1\.0.something`
-> `
{ 
"versions": {
  "1.0": {
    ...
  }
}`

**Comment by CrAfTsArMy** [comment]
Added! You can now use `\\` to escape the point.

Example:
`versions.1\\.0.something`
-> `{ "versions": { "1.0": { ... } }`
